version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - simplytransport-network
