"""Database Init

Revision ID: 1d1c9dc66800
Revises:
Create Date: 2024-08-17 13:52:59.217238

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d1c9dc66800"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ts_stop_times",
        sa.Column("Timestamp", sa.DateTime(), nullable=False),
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.PrimaryKeyConstraint("Timestamp", "id", name=op.f("pk_ts_stop_times")),
    )
    op.execute("SELECT create_hypertable('ts_stop_times', 'Timestamp');")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ts_stop_times")
    # ### end Alembic commands ###
