"""id sequence

Revision ID: 9fdbdd5e8677
Revises: ffcf1e5100cf
Create Date: 2024-09-25 16:26:44.007401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdbdd5e8677'
down_revision: Union[str, None] = 'ffcf1e5100cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE SEQUENCE ts_stop_times_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
            OWNED BY ts_stop_times.id;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE ts_stop_times_id_seq;")
