"""removing arrival_time

Revision ID: ffcf1e5100cf
Revises: 56f6a9c93651
Create Date: 2024-09-25 16:03:42.779436

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ffcf1e5100cf"
down_revision: str | None = "56f6a9c93651"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ts_stop_times", "actual_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ts_stop_times", sa.Column("actual_time", postgresql.TIME(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
