"""Create statistics table

Revision ID: 05a97210265c
Revises: c6fd373f53c5
Create Date: 2024-07-19 13:41:18.999045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy.types.datetime


# revision identifiers, used by Alembic.
revision: str = '05a97210265c'
down_revision: Union[str, None] = 'c6fd373f53c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_statistic',
    sa.Column('statistic_type', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database_statistic'))
    )
    op.create_index(op.f('ix_database_statistic_key'), 'database_statistic', ['key'], unique=False)
    op.create_index(op.f('ix_database_statistic_statistic_type'), 'database_statistic', ['statistic_type'], unique=False)
    op.create_index('ix_statistic_created_at', 'database_statistic', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_statistic_created_at', table_name='database_statistic')
    op.drop_index(op.f('ix_database_statistic_statistic_type'), table_name='database_statistic')
    op.drop_index(op.f('ix_database_statistic_key'), table_name='database_statistic')
    op.drop_table('database_statistic')
    # ### end Alembic commands ###
