version: "3.8"

services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector:0.147.0
    container_name: ot-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    command: "--config /etc/otelcol/config.yaml"
    volumes:
      - ../../deployment_linux/collector-config.yaml:/etc/otelcol/config.yaml
    environment:
      - ASPIRE_OTLP_ENDPOINT=${ASPIRE_OTLP_ENDPOINT:-aspire-dashboard:18889}
    restart: unless-stopped
    networks:
      - simplytransport-network
