"""Unique realtime trips

Revision ID: 614f1b6c195f
Revises: 5889d747e8a0
Create Date: 2024-10-09 20:29:18.389250

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "614f1b6c195f"
down_revision: str | None = "5889d747e8a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_rt_stop_time_stop_id_trip_id_stop_sequence", "rt_stop_time", type_="unique")
    op.create_unique_constraint(
        op.f("uq_rt_stop_time_stop_id"), "rt_stop_time", ["stop_id", "trip_id", "stop_sequence", "dataset"]
    )
    op.create_unique_constraint(op.f("uq_rt_trip_trip_id"), "rt_trip", ["trip_id", "route_id", "dataset"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_rt_trip_trip_id"), "rt_trip", type_="unique")
    op.drop_constraint(op.f("uq_rt_stop_time_stop_id"), "rt_stop_time", type_="unique")
    op.create_unique_constraint(
        "uq_rt_stop_time_stop_id_trip_id_stop_sequence",
        "rt_stop_time",
        ["stop_id", "trip_id", "stop_sequence", "dataset"],
    )
    # ### end Alembic commands ###
