"""Add unique constraint

Revision ID: 5889d747e8a0
Revises: 05a97210265c
Create Date: 2024-09-30 23:11:36.252571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5889d747e8a0'
down_revision: Union[str, None] = '05a97210265c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_rt_stop_time_stop_id_trip_id_stop_sequence"),
        "rt_stop_time",
        ["stop_id", "trip_id", "stop_sequence", "dataset"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_rt_stop_time_stop_id_trip_id_stop_sequence"),
        "rt_stop_time",
        type_="unique",
    )
    # ### end Alembic commands ###
