"""index lat and lon

Revision ID: f8b40d24637e
Revises: 614f1b6c195f
Create Date: 2025-02-23 23:34:58.142643

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8b40d24637e"
down_revision: str | None = "614f1b6c195f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_stop_coordinates", "stop", ["lat", "lon"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_stop_coordinates", table_name="stop")
    # ### end Alembic commands ###
