"""Cascade delete vehicle positions

Revision ID: 217582d889c2
Revises: f023ffb582f5
Create Date: 2024-01-28 01:28:15.951830

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "217582d889c2"
down_revision: str | None = "f023ffb582f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_rt_vehicle_trip_id_trip", "rt_vehicle", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_rt_vehicle_trip_id_trip"), "rt_vehicle", "trip", ["trip_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_rt_vehicle_trip_id_trip"), "rt_vehicle", type_="foreignkey")
    op.create_foreign_key("fk_rt_vehicle_trip_id_trip", "rt_vehicle", "trip", ["trip_id"], ["id"])
    # ### end Alembic commands ###
