"""created_at indexes

Revision ID: c6fd373f53c5
Revises: 4bcb531434be
Create Date: 2024-07-19 01:26:36.090711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fd373f53c5'
down_revision: Union[str, None] = '4bcb531434be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rt_stop_time_created_at', 'rt_stop_time', ['created_at'], unique=False)
    op.create_index('ix_rt_trip_created_at', 'rt_trip', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rt_trip_created_at', table_name='rt_trip')
    op.drop_index('ix_rt_stop_time_created_at', table_name='rt_stop_time')
    # ### end Alembic commands ###
