name: Format Code

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened]

jobs:
  Run_ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install dependencies
        run: pip install ruff==0.9.2

      - name: Verify pyproject.toml
        run: |
          if [ -f "pyproject.toml" ]; then
            echo "Using project's pyproject.toml"
          else
            echo "pyproject.toml not found"
            exit 1
          fi

      - name: Run Ruff check with fixes on main directory
        run: ruff check --fix SimplyTransport

      - name: Run Ruff check with fixes on tests directory
        run: ruff check --fix tests

      - name: Run Ruff format on main directory
        run: ruff format SimplyTransport

      - name: Run Ruff format on tests directory
        run: ruff format tests

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "[AUTOMATED] Format Code"
          add: "."
